const problems = [
  { title: "Kadane’s Algorithm (Max Subarray Sum)", 
    link: "https:/www.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1", 
    tags: ['Arrays', 'Dynamic Programming'], solved: false, attempted: false },
  { title: "Sort an array of 0s, 1s and 2s", 
    link: "https://www.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/1", tags: ['Arrays', 'Two Pointer'], solved: false, attempted: false },
  { title: "Subarray with Given Sum", link: "https://www.geeksforgeeks.org/problems/subarray-with-given-sum-1587115621/1", tags: ['Arrays', 'Sliding Window'], solved: false, attempted: false },
  { title: "Majority Element (> N/2 times)", link: "https://www.geeksforgeeks.org/problems/majority-element-1587115620/1", tags: ['Arrays', 'Hashing'], solved: false, attempted: false },
  { title: "Next Permutation", link: "https://www.geeksforgeeks.org/problems/next-permutation5226/1", tags: ['Arrays'], solved: false, attempted: false },
  { title: "Best Time to Buy and Sell Stock", link: "https://www.geeksforgeeks.org/problems/stock-buy-and-sell-1587115621/1", tags: ['Arrays', 'Greedy'], solved: false, attempted: false },
  { title: "Rotate Matrix by 90 degrees", link: "https://www.geeksforgeeks.org/problems/rotate-by-90-degree-1587115621/1", tags: ['Matrix', 'Simulation'], solved: false, attempted: false },
  { title: "Spiral Matrix", link: "https://www.geeksforgeeks.org/problems/spirally-traversing-a-matrix-1587115621/1", tags: ['Matrix'], solved: false, attempted: false },
  { title: "Find the Duplicate Number", link: "https://www.geeksforgeeks.org/problems/find-the-duplicate-number/1", tags: ['Arrays', 'Cycle Detection'], solved: false, attempted: false },
  { title: "Merge Intervals", link: "https://www.geeksforgeeks.org/problems/merge-intervals/1", tags: ['Greedy', 'Sorting'], solved: false, attempted: false },
  { title: "Two Sum", link: "https://www.geeksforgeeks.org/problems/two-sum/1", tags: ['Arrays', 'Hashing'], solved: false, attempted: false },
  { title: "Find Missing and Repeating", link: "https://www.geeksforgeeks.org/problems/find-missing-and-repeating/1", tags: ['Arrays', 'Math'], solved: false, attempted: false },
  { title: "Leaders in an Array", link: "https://www.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1", tags: ['Arrays'], solved: false, attempted: false },
  { title: "Move Zeroes to End", link: "https://www.geeksforgeeks.org/problems/move-all-zeroes-to-end-of-array/1", tags: ['Arrays', 'Two Pointer'], solved: false, attempted: false },
  { title: "Longest Consecutive Subsequence", link: "https://www.geeksforgeeks.org/problems/longest-consecutive-subsequence/1", tags: ['Arrays', 'Hashing'], solved: false, attempted: false },
  { title: "Minimum Platform", link: "https://www.geeksforgeeks.org/problems/minimum-platform/1", tags: ['Greedy', 'Sorting'], solved: false, attempted: false },
  { title: "Merge Without Extra Space", link: "https://www.geeksforgeeks.org/problems/merge-two-sorted-arrays/1", tags: ['Arrays'], solved: false, attempted: false },
  { title: "Count Inversions", link: "https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1", tags: ['Divide and Conquer'], solved: false, attempted: false },
  { title: "Equilibrium Point", link: "https://www.geeksforgeeks.org/problems/equilibrium-point-1587115620/1", tags: ['Arrays', 'Prefix Sum'], solved: false, attempted: false },
  { title: "Trapping Rain Water", link: "https://www.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1", tags: ['Arrays', 'Two Pointer'], solved: false, attempted: false },
  { title: "Chocolate Distribution Problem", link: "https://www.geeksforgeeks.org/problems/chocolate-distribution-problem3825/1", tags: ['Greedy'], solved: false, attempted: false },
  { title: "Array Subset of Another Array", link: "https://www.geeksforgeeks.org/problems/array-subset-of-another-array2317/1", tags: ['Hashing'], solved: false, attempted: false },
  { title: "Find the Element that Appears Once", link: "https://www.geeksforgeeks.org/problems/element-appears-once/1", tags: ['Bit Magic'], solved: false, attempted: false },
  { title: "Find Union of Two Arrays", link: "https://www.geeksforgeeks.org/problems/union-of-two-arrays3538/1", tags: ['Hashing'], solved: false, attempted: false },
  { title: "Longest Subarray with Sum K", link: "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1", tags: ['Hashing', 'Sliding Window'], solved: false, attempted: false },
  { title: "Prefix Sum Array", link: "https://www.geeksforgeeks.org/problems/prefix-sum-array/1", tags: ['Arrays', 'Prefix Sum'], solved: false, attempted: false },
  { title: "Find Pivot Index", link: "https://www.geeksforgeeks.org/problems/pivot-index/1", tags: ['Prefix Sum'], solved: false, attempted: false },
  { title: "Find the Transition Point", link: "https://www.geeksforgeeks.org/problems/find-transition-point-1587115620/1", tags: ['Binary Search'], solved: false, attempted: false },
  { title: "Max Circular Subarray Sum", link: "https://www.geeksforgeeks.org/problems/maximum-sum-circular-subarray-1587115620/1", tags: ['Arrays'], solved: false, attempted: false },
  { title: "Triplet Sum in Array", link: "https://www.geeksforgeeks.org/problems/triplet-sum-in-array-1587115621/1", tags: ['Two Pointer'], solved: false, attempted: false },
  { title: "Maximum Product Subarray", link: "https://www.geeksforgeeks.org/problems/maximum-product-subarray3604/1", tags: ['Arrays'], solved: false, attempted: false },
  { title: "Find First and Last Occurrence", link: "https://www.geeksforgeeks.org/problems/first-and-last-occurrences-of-x-1587115620/1", tags: ['Binary Search'], solved: false, attempted: false },
  { title: "Kth Smallest Element", link: "https://www.geeksforgeeks.org/problems/kth-smallest-element5635/1", tags: ['Heap'], solved: false, attempted: false },
  { title: "Median of Two Sorted Arrays", link: "https://www.geeksforgeeks.org/problems/median-of-two-sorted-arrays/1", tags: ['Binary Search', 'Divide and Conquer'], solved: false, attempted: false },
  { title: "Product Array Puzzle", link: "https://www.geeksforgeeks.org/problems/product-array-puzzle4525/1", tags: ['Arrays'], solved: false, attempted: false },
  { title: "Peak Element", link: "https://www.geeksforgeeks.org/problems/peak-element/1", tags: ['Binary Search'], solved: false, attempted: false },
  { title: "Stock Span Problem", link: "https://www.geeksforgeeks.org/problems/stock-span-problem-1587115621/1", tags: ['Stack'], solved: false, attempted: false },
  { title: "Largest Subarray with 0 Sum", link: "https://www.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1/1", tags: ['Hashing'], solved: false, attempted: false },
  { title: "Minimum Number of Jumps", link: "https://www.geeksforgeeks.org/problems/minimum-number-of-jumps-1587115620/1", tags: ['Greedy', 'DP'], solved: false, attempted: false },
  { title: "Find Number of Occurrences", link: "https://www.geeksforgeeks.org/problems/number-of-occurrence/1", tags: ['Binary Search'], solved: false, attempted: false },
  { title: "Buy and Sell Stock II", link: "https://www.geeksforgeeks.org/problems/stock-buy-and-sell-1587115621/1", tags: ['Greedy'], solved: false, attempted: false },
  { title: "Check if Array is Sorted and Rotated", link: "https://www.geeksforgeeks.org/problems/check-if-array-is-sorted-and-rotated/1", tags: ['Arrays'], solved: false, attempted: false },
  { title: "Find Duplicate in Array", link: "https://www.geeksforgeeks.org/problems/find-duplicate-in-array/1/1", tags: ['Arrays', 'Cycle Detection'], solved: false, attempted: false },
  { title: "Find Element in Sorted and Rotated Array", link: "https://www.geeksforgeeks.org/problems/search-in-a-rotated-array4618/1", tags: ['Binary Search'], solved: false, attempted: false },
  { title: "Rearrange Array Alternately", link: "https://www.geeksforgeeks.org/problems/rearrange-array-alternately/1", tags: ['Arrays'], solved: false, attempted: false },
  { title: "Count Pairs with Given Sum", link: "https://www.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1", tags: ['Hashing'], solved: false, attempted: false },
  { title: "Maximum Sum Increasing Subsequence", link: "https://www.geeksforgeeks.org/problems/maximum-sum-increasing-subsequence4749/1", tags: ['DP'], solved: false, attempted: false },
  { title: "Find Missing Number", link: "https://www.geeksforgeeks.org/problems/missing-number-in-array1416/1", tags: ['Math'], solved: false, attempted: false }
  ]
export default problems;
